-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kilpailu CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Hevonen CASCADE;
DROP TABLE IF EXISTS Osallistuminen CASCADE;